# docker-compose.yml – MALARIA_DETECTION
# Auteur : Papa Malick NDIAYE | Master DSGL – UADB

services:
  malaria-api:
    image: malaria-detection:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: malaria_detection_api
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - FLASK_ENV=production
    volumes:
      - ./models:/app/models
      - ./metrics:/app/metrics
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test        : ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval    : 30s
      timeout     : 10s
      retries     : 3
      start_period: 60s
